version: '3.8'

services:
  system:
    build: 
      context: .
      dockerfile: ./docker/system/Dockerfile
    env_file:
      - .env
    volumes:
      - ./flaskr-tdd/project/templates:/app/project/templates
      - ./flaskr-tdd/project/static:/app/project/static
  
  web:
    build: 
      context: .
      dockerfile: ./docker/build/Dockerfile
    ports:
      - "5052:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      system:
        condition: service_completed_successfully
    volumes:
      - ./flaskr-tdd/project/templates:/app/project/templates
      - ./flaskr-tdd/project/static:/app/project/static

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
