version: '3.8'

services:
  backend:
    image: backend
    build: ./spring-backend
    env_file: ./spring-backend/.env
    volumes:
      - maven-cache:/root/.m2 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - react-spring-network

  frontend:
    image: frontend
    build: ./react-frontend
    env_file: ./react-frontend/.env
    volumes:
      - frontend-deps:/app/node_modules
      - ./react-frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - react-spring-network

  nginx-proxy:
    image: nginx-proxy
    build: ./nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - react-spring-network


  db:
    image: mysql:9
    env_file: ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - react-spring-network

volumes:
  maven-cache:
  frontend-deps:
  mysql-data:

networks:
  react-spring-network:
